[profile.default]
extends = "../foundry.base.toml"
src = "contracts"
out = "out"
libs = ["../lib"]
no_match_coverage = "contracts/mocks/.*|scripts/*"

remappings = [
    "forge-std/=../lib/forge-std/src/",
    "@openzeppelin/contracts/=../lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=../lib/openzeppelin-contracts-upgradeable/contracts/",
    "openzeppelin-foundry-upgrades/=../lib/openzeppelin-foundry-upgrades/src/",
    "diamond-contracts-core/=../core/contracts/",
    "diamond-contracts-dao/=../dao/contracts/",
]

[fmt]
line_length = 120
bracket_spacing = true
wrap_comments = true

[doc]
ignore = ["**/*.t.sol"]
out = "docs"
repository = "https://github.com/DMDcoin/contracts-monorepo/views"
